// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Models.Navigation.AddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GPS")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuburbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitNum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StreetTypeId");

                    b.HasIndex("SuburbId");

                    b.ToTable("Address", "TPT");
                });

            modelBuilder.Entity("Models.Navigation.RouteAddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteAddress", "TPT");
                });

            modelBuilder.Entity("Models.Navigation.RouteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Distance")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Route", "TPT");
                });

            modelBuilder.Entity("Models.Navigation.StreetTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Common")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StreetType", "TPT");
                });

            modelBuilder.Entity("Models.Navigation.SuburbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suburb", "TPT");
                });

            modelBuilder.Entity("SampleCode.Other.SettingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Setting", "TPT");
                });

            modelBuilder.Entity("SampleCode.Other.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultUser")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SettingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettingId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", "TPT");
                });

            modelBuilder.Entity("Models.Navigation.AddressModel", b =>
                {
                    b.HasOne("Models.Navigation.StreetTypeModel", "StreetType")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Navigation.SuburbModel", "Suburb")
                        .WithMany("Addresses")
                        .HasForeignKey("SuburbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreetType");

                    b.Navigation("Suburb");
                });

            modelBuilder.Entity("Models.Navigation.RouteAddressModel", b =>
                {
                    b.HasOne("Models.Navigation.AddressModel", "Address")
                        .WithMany("RouteAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Navigation.RouteModel", "Route")
                        .WithMany("RouteAddresses")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SampleCode.Other.SettingModel", b =>
                {
                    b.HasOne("SampleCode.Other.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SampleCode.Other.UserModel", b =>
                {
                    b.HasOne("SampleCode.Other.SettingModel", "CurrentSetting")
                        .WithMany()
                        .HasForeignKey("SettingId");

                    b.Navigation("CurrentSetting");
                });

            modelBuilder.Entity("Models.Navigation.AddressModel", b =>
                {
                    b.Navigation("RouteAddresses");
                });

            modelBuilder.Entity("Models.Navigation.RouteModel", b =>
                {
                    b.Navigation("RouteAddresses");
                });

            modelBuilder.Entity("Models.Navigation.StreetTypeModel", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Models.Navigation.SuburbModel", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
